# Copy this file to:
# C:\Program Files\Zabbix Agent 2\zabbix_agent2.d\active-directory.conf
#
# Copy AdHealth.ps1 to:
# C:\Program Files\Zabbix Agent 2\scripts\AdHealth.ps1

UserParameter=ad.sysvol_netlogon.shares,powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\scripts\AdHealth.ps1" -Check Shares
UserParameter=ad.dns.srv_lookup,powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\scripts\AdHealth.ps1" -Check DnsSrv
UserParameter=ad.replication.failures,powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\scripts\AdHealth.ps1" -Check ReplicationFailures
UserParameter=ad.replication.oldest_age,powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\scripts\AdHealth.ps1" -Check ReplicationAge
